### ISSUE TITLE
Implement rewards distribution

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1413]
## Epic Description

Implement rewards distribution for validators. Rewarded activities are:

- creating dag blocks (basically number of included unique txs is what is rewarded)
- creating pbft block(fixed reward)
- voting - pbft block author includes all votes from previous pbft block - he should be motivated to include more than 2/3+1 votes by getting more rewards if he does

#### High level design

- C++ gathers rewards statistics (number of unique txs included by each dag proposer, number of votes, ....) and sends it to the go part
- Go calculates generated block reward (based on %yield and block production rate)
- Go calculates rewards for all delegators, who will receive some part(proportional to their delegation) of validator's reward
- Go writes rewards to the staking contract(bypasses evm due to performance issues)

## List of Tasks (Complete in order)
1. [ ] [Task 1: Calculate rewards statistics(C++)](https://github.com/Taraxa-project/taraxa-node/issues/1414).
2. [ ] [Task 2: Implement staking contract](https://github.com/Taraxa-project/taraxa-node/issues/1415).
3. [ ] [Task 3: Implement no-evm SC interface](https://github.com/Taraxa-project/taraxa-node/issues/1416).
4. [ ] [Task 4: Calculate block reward based on yield curve](https://github.com/Taraxa-project/taraxa-node/issues/1605)
5. [ ] [Task 5: Include previous pbft block votes hashes in proposed pbft block](https://github.com/Taraxa-project/taraxa-node/issues/1604).
6. [ ] [Task 6: Connect rewards code modules](https://github.com/Taraxa-project/taraxa-node/issues/1417).
