### ISSUE TITLE
Economics

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1427]
## Category Description

Only economics-related tasks are part of this category, e.g. block rewards distribution, fees adjustments, etc...

_Note_: "Roadmap category" issues are not real issues that will be solved. It is used for tracking progress of tasks that are part of Taraxa Roadmap

## List of Tasks (Complete in order)
1. [ ] [Task 1: Implement rewards distribution](https://github.com/Taraxa-project/taraxa-node/issues/1413).
2. [ ] [Task 2: Classic firts-price auction transaction fees](https://github.com/Taraxa-project/taraxa-node/issues/1425).
3. [ ] [Task 3: Fee predictability](https://github.com/Taraxa-project/taraxa-node/issues/1426).
