### ISSUE TITLE
DDoS protection

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1428]
## Epic Description

Eliminate unintentional traffic flooding behaviors 

## List of Tasks (Complete in order)
1. [x] [Task 1: Limit internal structures sizes](https://github.com/Taraxa-project/taraxa-node/issues/1432).
2. [x] [Task 2: Limit packets queue size](https://github.com/Taraxa-project/taraxa-node/issues/1431).
3. [x] [Task 3: Limit peer bandwidth](https://github.com/Taraxa-project/taraxa-node/issues/2244).
