### ISSUE TITLE
security

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1429]
## List of Tasks (Complete in order)
1. [ ] [Task 1: DDoS protection ](https://github.com/Taraxa-project/taraxa-node/issues/1428).
2. [ ] [Task 2: Strict gossip rules](https://github.com/Taraxa-project/taraxa-node/issues/1433).
3. [ ] [Task 3: Peers blacklisting](https://github.com/Taraxa-project/taraxa-node/issues/1434).
4. [ ] [Task 4: Third-party audits](https://github.com/Taraxa-project/taraxa-node/issues/1435).
5. [ ] [Task 5: Security bounties](https://github.com/Taraxa-project/taraxa-node/issues/1436).

## Category Description

Only security-related tasks are part of this category, e.g. ddos protection, etc...

_Note_: "Roadmap category" issues are not real issues that will be solved. It is used for tracking progress of tasks that are part of Taraxa Roadmap
