### ISSUE TITLE
dapp

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1439]
## List of Tasks (Complete in order)
1. [ ] [Task 1: GraphQL for better queries](https://github.com/Taraxa-project/taraxa-node/issues/1440).
2. [ ] [Task 2: Developer documentation](https://github.com/Taraxa-project/taraxa-node/issues/1441).
3. [ ] [Task 3: DApp examples](https://github.com/Taraxa-project/taraxa-node/issues/1442).

## Category Description

Only Dapp-related tasks are part of this category, e.g. graphql support, etc...

_Note_: "Roadmap category" issues are not real issues that will be solved. It is used for tracking progress of tasks that are part of Taraxa Roadmap
