### ISSUE TITLE
perfomance

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1447]
## List of Tasks (Complete in order)
1. [ ] [Task 1: CPU optimization](https://github.com/Taraxa-project/taraxa-node/issues/1443).
2. [ ] [Task 2: PBFT block size limit](https://github.com/Taraxa-project/taraxa-node/issues/1406).
3. [ ] [Task 3: Database optimizations](https://github.com/Taraxa-project/taraxa-node/issues/1444).
4. [ ] [Task 4: Light node](https://github.com/Taraxa-project/taraxa-node/issues/1445).
5. [ ] [Task 5: Network-wide stress tests](https://github.com/Taraxa-project/taraxa-node/issues/1446).

## Category Description

Only performance-related tasks are part of this category, e.g. CPU optimization, etc...

_Note_: "Roadmap category" issues are not real issues that will be solved. It is used for tracking progress of tasks that are part of Taraxa Roadmap
