### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1452]
## List of Tasks (Complete in order)
1. [ ] [Task 1: TPS benchmark](https://github.com/Taraxa-project/taraxa-node/issues/1448).
2. [ ] [Task 2: Latency benchmark](https://github.com/Taraxa-project/taraxa-node/issues/1449).
3. [ ] [Task 3: DApp-based benchmark](https://github.com/Taraxa-project/taraxa-node/issues/1450).
4. [ ] [Task 4: Minimum system requirement](https://github.com/Taraxa-project/taraxa-node/issues/1451).

## Category Description

Only benchmark-related tasks are part of this category, e.g. TPS benchmark, etc...

_Note_: "Roadmap category" issues are not real issues that will be solved. It is used for tracking progress of tasks that are part of Taraxa Roadmap
