### ISSUE TITLE
Transaction ordering & delegation process

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#1480]
## Epic Description

Currently testnet is stalled due to multiple bugs, due to which our consensus nodes lost majority of voting power. Some bugs are related to ledger, some to the community site, which triggers delegation/undelegation process. 

### Problem 1 - Dag block txs ordering
Ledger is not correctly ordering transactions when creating dag blocks. We keep unexecuted txs inside unordered map and when creating dag block, 250 txs are retrieved from unordered map by iterating over the map from the beginning - this means those 250 txs are basically random. Then they are ordered by sender & nonce. Problem is that for example if there is 10k txs in tx pool already and sender A sends 2 txs: TX1 with nonce 1 and fee 10 and TX2 with nonce 2 and fee 5, it is possible that due to randomness TX2 will be saved at the beggining of the transaction pool and TX1 at the end, so TX2 will be executed first and fails due to invalid nonce.... This should never happen

##### Solution
Create much more sophisticated tx pool, which would serve 250 ordered txs based on fee & sender & nonce ?
See eth ordering algo here: 
https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/core/types/transaction.go#L372

### Problem 2 - Pbft block txs ordering
Even if we fix txs ordering based on fee & sender & nonce, dag could still shuffle dag blocks inside single pbft blocks so txs could be again ordered in a wrong way. 

##### Solution
Once the pbft block is created and dag blocks ordered, take the final ordering of txs in it and swap those based on sender & nonce or sender & fee ? Not sure which algorithm to choose but from implementation point of view it does not matter. 

### Problem 3 - No forefront tx execution check on tmp state
We allow processing of invalid txs. Nice example is current mainnet where all txs fail due to insufficient balance but we broadcast them as valid, they are included in dag&pbft blocks, drain resources of our validators and they are useless...

##### Solution
Tx could be executed on some tmp test state and if it does not succeed, it will be rejected.

### Problem 4 - More sophisticated delegation process
Delegation process might need to be more sophisticated than it is at the moment. It does not check receipts of txs so it is possible to get into the situation when multiple users will register and unregister multiple times in short amount of time. Now because of the txs ordering bug inside the ledger, all undelegations for our nodes could be ordered in tx pool at the beginning and undelegations for user node could be ordered at the end. During repetitive registering, delegations for user node could be ordered at the beginning of the tx pool, delegations for our nodes could be ordered at the end. That is how we can end up in a situation when few blocks are executed and we loose majority of voting power ! 

##### Solution

- delegation process could check receipts for all txs it makes and not enable new delagation/undelegations for the same address until previous ones are executed
- register could be blocked for N hours since the unregister was triggered
 
!!! IMPORTANT NOTE: this might be solved (probably ?) by other tasks from this epic, but it would be nice to have such robust delegation process anyway so there would be no way to end up in the same state again

### Problem 5 - More sophisticated faucet
Faucet is constantly sending new txs even if the network stalls, which makes a lot of problems and even if the network does not stall but we are not able to process txs fast enough, it creates ordering problems described above

##### Solution
Check tx pool size and if it is bigger > N, do not send new txs

!!! IMPORTANT NOTE: this might be solved (probably ?) by other tasks from this epic, but it would be nice to have such robust faucet anyway so there would be no way to end up in the same state again

## List of Tasks (Complete in order)
1. [x] [Task 1: Dag block txs ordering](https://github.com/Taraxa-project/taraxa-node/issues/1481).
2. [x] [Task 2: Pbft block txs ordering](https://github.com/Taraxa-project/taraxa-node/issues/1482).
3. [x] [Task 3: No forefront tx execution check on tmp state](https://github.com/Taraxa-project/taraxa-node/issues/1483).
4. [ ] [Task 4: More sophisticated delegation process](https://github.com/Taraxa-project/taraxa-node/issues/1484).
5. [ ] [Task 5: More sophisticated faucet](https://github.com/Taraxa-project/taraxa-node/issues/1484).
