### ISSUE TITLE
Pbft consensus design/code cleanup

### ISSUE THREAD

**Issue by JakubFornadel** [Taraxa-project/taraxa-node#2048]
## Epic Description

We did a lot of work already refactoring our pbft consensus design/code.  Now that we know that part of node node much better, we could start the next phase of refactor to make the flow even easier to understand and therefore also adjust.

Note: first 2 tasks are the most important, the rest are basically further cleanup of previous design

## List of Tasks (Complete in order)
1. [x] [Task 1: Refactor VotesSync and Vote packets](https://github.com/Taraxa-project/taraxa-node/issues/2031).
2. [x] [Task 2: Remove next votes manager](https://github.com/Taraxa-project/taraxa-node/issues/2047).
3. [x] [Task 3: Refactor db saving of soft/cert-voted blocks](https://github.com/Taraxa-project/taraxa-node/issues/2046).
4. [x] [Task 4: Do not enter consensus steps if node is not eligible](https://github.com/Taraxa-project/taraxa-node/pull/2044).
5. [x] [Task 6: Optimize vote structure rlp](https://github.com/Taraxa-project/taraxa-node/issues/2039).
6. [x] [Task 7: Refactor PbftMgrPreviousRoundStatus db fields](https://github.com/Taraxa-project/taraxa-node/issues/2032).

**Comment by JakubFornadel** [comment]
@justinsnapp can you pls read through tasks 2 and 5 if you see any potential problems with it ?
